# Generated by Django 4.2.2 on 2023-06-27 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-date_added',), 'verbose_name_plural': 'Categories'},
        ),
    ]
