# Generated by Django 4.2.2 on 2023-07-08 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='stripe_token',
            new_name='stripe_session_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='paid_amount',
            new_name='total_amount',
        ),
    ]
