# Generated by Django 4.2.2 on 2023-12-09 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
