# Generated by Django 4.2.2 on 2023-07-08 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_rename_stripe_token_order_stripe_session_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='quantity',
            new_name='count',
        ),
    ]
