# Generated by Django 4.2.2 on 2023-07-08 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_rename_quantity_orderproduct_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='lastName',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='phoneNumber',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='street1',
            new_name='street_1',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='street2',
            new_name='street_2',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='zipCode',
            new_name='zip_code',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='price',
        ),
    ]
