# Generated by Django 4.2.2 on 2024-01-30 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_rename_stripe_session_id_order_checkout_session_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='street_2',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
    ]
