# Generated by Django 4.2.2 on 2023-07-08 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_rename_firstname_order_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='street_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
