# Generated by Django 4.2.2 on 2024-01-30 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_orderproduct_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_amount',
            new_name='total',
        ),
    ]
